### ISSUE TITLE
supernova --debug fails

### ISSUE THREAD

**Issue by supermari0** [major/supernova#103]
I see "error: argument <subcommand>: invalid choice: u'--debug '" when attempting to use --debug mode in nova using supernova. Using supernova v2.0.9.

**Comment by major** [comment]
Sorry for the long delay.  This was fixed in https://github.com/major/supernova/commit/35fd8e41cb6932e976d232fdec8904bcf3872c9b -- does that work for you?

**Comment by supermari0** [comment]
Sorry for the delayed response as well.

I'm having some trouble getting this working, but it appears to be a problem either with rackspace-novaclient or my local environment. I started off with a simple python setup.py install in a virtualenvenv I created with Python 2.7.10. I then realized that to use this with Rackspace auth I'd need rackspace-novaclient, so I pip uninstalled python-novaclient and pip installed rackspace-novaclient (all still in a venv).

I'm seeing this:

```
> supernova dfw list                                                                                                                                            
[SUPERNOVA] Running nova against dfw... 

__ Error Output ______________________________________________________________
Version 1.1 is deprecated, using alternative version 2 instead.
/Users/mariojv/venv/lib/python2.7/site-packages/novaclient/shell.py:609: UserWarning: novaclient auth plugins that are not keystone are deprecated. Auth plugins should now be done as plugins to keystoneauth and selected with --os-auth-type or OS_AUTH_TYPE
  'novaclient auth plugins that are not keystone are deprecated.'
/Users/mariojv/venv/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for identity.api.rackspacecloud.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
ERROR (AttributeError): ImpImporter instance has no attribute 'load_module'
```

I doubt this is the same bug as this issue though and have a feeling I'm just doing something wrong on my end, so feel free to close this. I'll see if I can get through this particular issue and re-open if I still see the problem.

Thank you!

**Comment by supermari0** [comment]
I fixed the problem by forcing python-novaclient to a version <3.0.0. I think the issue that occurred is the same as this one: https://github.com/rackerlabs/rackspace-novaclient/issues/14

After pinning that and upgrading setuptools I was able to run supernova dfw --debug list successfully with the expected output. Thanks!
