### ISSUE TITLE
ImportError: No module named xmlrpc_client

### ISSUE THREAD

**Issue by djjonno** [major/supernova#55]
Traceback (most recent call last):
  File "/usr/local/bin/supernova", line 9, in <module>
    load_entry_point('supernova==1.0.2', 'console_scripts', 'supernova')()
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/Library/Python/2.7/site-packages/supernova/executable.py", line 31, in <module>
    from . import supernova
  File "/Library/Python/2.7/site-packages/supernova/supernova.py", line 24, in <module>
    from novaclient import client as novaclient
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 45, in <module>
    from novaclient import utils
  File "/Library/Python/2.7/site-packages/novaclient/utils.py", line 27, in <module>
    from novaclient.openstack.common import jsonutils
  File "/Library/Python/2.7/site-packages/novaclient/openstack/common/jsonutils.py", line 52, in <module>
    import six.moves.xmlrpc_client as xmlrpclib
ImportError: No module named xmlrpc_client

**Comment by dblacka** [comment]
I ran into this problem as well using Yosemite's system python. The actual issue is that the *six.py* that comes with the system python doesn't define the *six.moves.xmlrpc_client* alias, but the version installed via pip into site-packages does.  To fix it, we just need to get site-packages in the python path (i.e., sys.path) before the path to the system-provided version.   Interestingly, using 'easy_install' to install six works, because easy_install will add the /Library/Python/2.7/site-packages path to ../site-packages/easy-install.pth file, which has a bit of code in it to force those paths to the front.

**Comment by lxstar** [comment]
@dblacka thanks. 
I upgrade openstack_dashboard requirement and same program `ImportError: No module named xmlrpc_client`

and 

`pip uninstall six`
`easy_install six`

so success.

**Comment by christx2** [comment]
worked for me too, looks like /Library/Python/2.7/site-packages now contains all six packages, and
that does the trick with the existing OSX python (I'm ok with it), no more xmlrpc error with keystone clients. cheers.

**Comment by fiorix** [comment]
`easy_install` works but requires root on OS X, which is not ideal. `pip install --user` installs just fine but then `heat` and other programs fail with the `ImportError: No module named xmlrpc_client`.

I'm currently using `pip` on virtualenv and it works fine.

**Comment by rashmi-cliqr** [comment]
I had to reinstall XCODE and run :
pip uninstall six
easy_install six

It solved the "ImportError: No module named xmlrpc_client" for yosemite os for me

**Comment by gkesavan** [comment]
I had the same module missing issue but uninstalling modules and installing them using easy_install fixed the issue, thanks @haoquanwang for the suggestion. it works.

**Comment by rameshhp** [comment]
I was facing this issue on Yosemite and I followed the instructions that @haoquanwang gave.  That has helped.  Thanks @haoquanwang!

**Comment by christx2** [comment]
Btw, virtualenv is an epiphany for me. If you have not tried it, give it a go for openstack clients, and avoiding a repeat of the xmlrpc error (which keeps occurring after an easy_install update) for me.
Highly recommend as this root user side installation of python and xcode don't seem to like each other.

**Comment by zhuronghua** [comment]
thanks @dblacka. easy_install six works!

**Comment by IrvingSun** [comment]
thanks ,it works!@dblacka

**Comment by Muscliy** [comment]
when i start create my project , the terminal tell me:
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Library/Python/2.7/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/Library/Python/2.7/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Library/Python/2.7/site-packages/scrapy/http/__init__.py", line 12, in <module>
    from scrapy.http.request.rpc import XmlRpcRequest
  File "/Library/Python/2.7/site-packages/scrapy/http/request/rpc.py", line 7, in <module>
    from six.moves import xmlrpc_client as xmlrpclib
ImportError: cannot import name xmlrpc_client

**Comment by Muscliy** [comment]
i have fixed , from 
http://stackoverflow.com/questions/30964836/scrapy-throws-importerror-cannot-import-name-xmlrpc-client

**Comment by superdump** [comment]
This has a pretty good description of the issue and a possible workaround, although perhaps the PYTHONPATH environment variable workaround is better: http://stackoverflow.com/questions/27668081/how-to-install-six-moves-xmlrpc-client

**Comment by yrsamrith** [comment]
Did you try this? It worked for me.

sudo rm -rf /Library/Python/2.7/site-packages/six*
sudo rm -rf /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six*
sudo pip install six

**Comment by superdump** [comment]
I'm not sure removing files from a system framework is a good idea.

**Comment by rashmi-cliqr** [comment]
Removing and installing six worked for me as well...

**Comment by superdump** [comment]
The workaround noted by @yrsamrith can work, but I don't think it is a good idea to permanently remove files from a system framework. Perhaps other applications are dependent on those files. How do you get them back? What if you need to use both nova and the other application simultaneously? It's not a good solution.

**Comment by yrsamrith** [comment]
@superdump i agreed. But i think what i did is only cleanly remove "six" package, then reinstall it. Correct if i am wrong.

**Comment by superdump** [comment]
You removed the package from /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six* which is part of the Python framework on OS X. When you run pip install, it will then be installed, I expect, to /Library/Python/2.7/site-packages/six. The six that is part of Python.framework is gone. Maybe some application is dependent on that specific version and now you can't get it back.

**Comment by p0123n** [comment]
Ty @superdump, your solution with PYTHONPATH works! 

> sudo rm -rf /Library/Python/2.7/site-packages/six*
Guys, if you don't want, you don't need to remove old six version, you can just backup it to the somethig like six.py.bak It works also.

**Comment by pilasguru** [comment]
The solution of @dblacka dated Jan 13 works for me  (thank you!)
(Yosemite and I run all pip and easy_install commands as root)

**Comment by v1k0d3n** [comment]
another plug for @haoquanwang. worked like a charm!

**Comment by gvelu** [comment]
only doing below works for me.
pip uninstall six
easy_install six
It solved the "ImportError: No module named xmlrpc_client" for yosemite os for me
]$nova --version
2.35.0

**Comment by zhumojun** [comment]
I solved this issue by reinstall the package via easy_install
