### ISSUE TITLE
Quoted arguments are not processed correctly

### ISSUE THREAD

**Issue by thesquelched** [major/supernova#81]
Quoted arguments are not respected ever since a5e9c2a9ce4d48c6acf37e481b6464ba2c9e7aa7 (when the `click` stuff was introduced, although `click` itself supports quoted arguments).  It seems as though the quotes are stripped at some point, causing a variety of issues.  For example:

Contents of `$HOME/bin/quote`:

```python
#!/usr/bin/env python

import sys
print sys.argv
```

Contents of `$HOME/.supernova` (doesn't really matter, but just to illustrate that I have a valid config):

```
[dev]
FOO=bar
```
Running the script with two arguments works correctly, but if I use one quoted argument with a space in it, `supernova` still registers it as two arguments:

```bash
$ supernova -x quote dev foo bar
[SUPERNOVA] Running test against ord...
['/Users/thesquelched/bin/quote', 'foo', 'bar']

$ supernova -x quote dev "foo bar"
[SUPERNOVA] Running test against ord...
['/Users/thesquelched/bin/quote', 'foo', 'bar']

$ supernova -x quote dev 'foo bar'
[SUPERNOVA] Running test against ord...
['/Users/thesquelched/bin/quote', 'foo', 'bar']
```

Note that the result should be `['/Users/thesquelched/bin/quote', 'foo bar']`

**Comment by major** [comment]
Thanks for the report. I'll take a look at this one to see what I can figure out.
