### ISSUE TITLE
Supernova Lint? & some common problems I had with Yosemite MAC OSX and supernova

### ISSUE THREAD

**Issue by aziouk** [major/supernova#85]
Hello Major Hayden,

thanks for writing Supernova. Although I'm not too afraid of using environment variables in nova without this wrapper, it certainly is very helpful to have a format for separate regions and customer accounts in a configuration file.

I actually use Mac OS X yosemite, and had quite a few problems with deprecated nova calls from the wrapper, the dreaded xml library issue a lot have reported in the past. I managed to fix this and some other issues I encountered by installing all the required dependencies with pip, such as the auth lib, cliutils, and --upgrading etc etc. Do not tell me why but for some reason they weren't installed when running easy_install. So i tried cloning from the latest github release as described in the documentation. I saw in previous comments by you that you weren't able to reproduce the error, which might be something to do with the software provided with yosemite distribution. For anyone interested I was able to resolve some issues as well by running a pip freeze | xargs pip uninstall -y and reinstalling from scratch a couple of times to go thru each error. I even resorted to brew, which I wanted to try and avoid. I included some details of the issues I was having on my blog at:

 http://www.haxed.me.uk/index.php/2015/07/29/argumentative-supernova-and-python-pip/

but I digress.. after resolving a lot of the problems I mention in the blog above,

I had then inadvertently added an additional character to the .supernova config and started to get some errors like:

 File "/usr/local/bin/supernova", line 9, in <module>
    load_entry_point('supernova==2.0.3', 'console_scripts', 'supernova')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/supernova/executable.py", line 105, in run_supernova
    nova_creds = config.run_config(config_file_override=conf)
  File "/usr/local/lib/python2.7/site-packages/supernova/config.py", line 34, in run_config
    nova_creds = load_config(config_file_override)
  File "/usr/local/lib/python2.7/site-packages/supernova/config.py", line 45, in load_config
    nova_creds = ConfigObj(supernova_config)
  File "/usr/local/lib/python2.7/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/site-packages/configobj.py", line 1318, in _load

After a lot of head scratching , reinstalling and then remaking the .supernova config several times it appeared that the problem and time spent head scratching was because of the format of .supernova file. Would it be possible potentially to have a lint function added to supernova to provide more helpful errors?

Also I noticed in the rack 'quickstart' documentation at: 

http://supernova.readthedocs.org/en/latest/raxquickstart/

it is mentioned in the reference .supernova file to use:

supernova-keyring -s global RackspaceAccountUser
supernova-keyring -s global RackspaceAccountAPIKey
supernova-keyring -s global RackspaceAccountDDI

which works for mycloud admirably, however there is no mention in the external or internal documentation about the difference between admin OS_AUTH_URL's which work differently!

RackspaceSSOusername or RackspaceSSOpassword

This for me caused some confusion in setting up the supernova and I can sincerely and humbly appreciate that supernova as it is an extremely powerful and is becoming an increasingly complex beast, but these small features in the documentation and a lint could significantly increase usability and help non python-esque users differentiate between configuration errors and dependency or plugin difficulties.

Thank you for writing supernova once again! I can only hope that this information might save some people a couple of hours that experience the same problems as me when following the documentation 

Best wishes,
Adam

**Comment by major** [comment]
Hey @aziouk, thanks for the detailed issue!  You're right on the lint problem -- there does need to be a more friendly error message thrown when it's not possible to parse the configuration file properly.

I also need to shore up some of the documentation about the configuration file as well.  If you have suggestions for better wording, feel free to submit a pull request and I'll review it.

I read through your blog post, and I did see that you had some issues with `rackspace-novaclient`.  I've considered making that a requirement for supernova during installation but it's not really applicable for someone using supernova/nova with another cloud outside of Rackspace (take HP's OpenStack cloud, for example).  If the majority of users are using supernova with Rackspace's cloud, adding `rackspace-novaclient` as a required package seems to make sense.  I'll think this one over a bit and I might add a warning during the installation with a suggestion to install additional packages.

**Comment by aziouk** [comment]
Hey Major Hayden,

Thank you for the kind and generous commits adding the lint functionality to supernova. That was very, very quick! I am convinced that the new lint feature will benefit users!

I must say that the documentation you provide already is already excellent. I had a couple of unusual problems though that weren't covered. If there was one thing I struggled to understand it was probably the differences between the admin vs the customer facing url's. i.e. the admin urls required differently formed configuration and credentials to work properly (for instance an API KEY does not appear to be used with admin function in supernova wrapper). I struggled with this until I realised the difference. That mainly happened because of the top of the .supernova file only mentions the customer configurations:

# To begin using this sample configuration file, drop it into ~/.supernova and
# run these commands to add credentials to your keyring:
#
#    supernova-keyring -s global RackspaceAccountUser
#    supernova-keyring -s global RackspaceAccountAPIKey
#    supernova-keyring -s global RackspaceAccountDDI
#

Potentially it might be useful to make the determination in the internal rackspace documentation. I think any and all of my problems when I'd solved dep problems, were mainly related to this difficulty, I can certainly say though I have learned a lot more in the process, which is excellent! 

Thank you once again for your time Major,

Best wishes,
Adam

**Comment by major** [comment]
Thanks, @aziouk! I'll pass along that feedback to the docs folks at Rackspace.
