### ISSUE TITLE
Check for rackspace-novaclient

### ISSUE THREAD

**Issue by major** [major/supernova#86]
(Carrying over from #85)

Adding `rackspace-novaclient` as a required package may not be the best idea, but we should have a way to alert users that the package isn't installed if they're actively trying to talk to Rackspace's cloud.

**Comment by carlgeorge** [comment]
Would this be a good use case for setuptools' [extras](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)?

```python
    extras_require = {
        'rackspace':  ['rackspace-novaclient']
    }
```

This would allow users to run `pip install supernova[rackspace]` and get the desired setup (I think).

**Comment by major** [comment]
That's not a bad idea. Want to put in a PR? :)

**Comment by carlgeorge** [comment]
Tug #98 submitted.
